# Start from the 4.0.1 base
FROM apache/spark:4.0.1-java21-python3

USER root

ENV SPARK_HOME=/opt/spark
ENV PATH="$SPARK_HOME/bin:$SPARK_HOME/sbin:${PATH}"

# User management
RUN usermod -u 1000 -d /home/spark -m spark && \
    groupmod -g 1000 spark || true

RUN apt-get update && apt-get install -y wget curl && \
    rm -rf /var/lib/apt/lists/*

# Correct PySpark and Delta Spark versions
RUN pip install --no-cache-dir \
    pyspark==4.0.1 \
    pandas \
    pyarrow \
    grpcio \
    grpcio-status \
    zstandard \
    mysql-connector-python \
    delta-spark==4.0.1

WORKDIR /opt/spark/jars

# EXHAUSTIVE JAR LIST FOR SPARK 4.0.1 + MINIO
# We use Hadoop 3.4.2 and AWS SDK V2 Bundle
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.1/hadoop-aws-3.4.1.jar && \
    wget https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.25.53/bundle-2.25.53.jar && \
    wget https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.5.0/mysql-connector-j-9.5.0.jar && \
    wget https://repo1.maven.org/maven2/io/delta/delta-spark_2.13/4.0.1/delta-spark_2.13-4.0.1.jar && \
    wget https://repo1.maven.org/maven2/io/delta/delta-storage/4.0.1/delta-storage-4.0.1.jar

# Finalizing permissions
RUN chown -R spark:spark /opt/spark && \
    chmod -R 775 /opt/spark

RUN mkdir -p /home/spark/.ivy2 && chown -R spark:spark /home/spark
ENV IVY_HOME=/home/spark/.ivy2
ENV HOME=/home/spark

WORKDIR /opt/spark
USER 1000