spark.sql.warehouse.dir              s3a://spark-warehouse/

# Konfiguracja uwierzytelniania w MinIO
spark.hadoop.fs.s3a.endpoint         http://minio:9000
spark.hadoop.fs.s3a.access.key       admin
spark.hadoop.fs.s3a.secret.key       password
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl             org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

# Włączanie logowania zdarzeń
spark.eventLog.enabled           true
spark.eventLog.dir               s3a://spark-logs/

# Konfiguracja History Servera
spark.history.fs.logDirectory    s3a://spark-logs/

# Dynamic allocation
spark.dynamicAllocation.enabled true
spark.dynamicAllocation.shuffleTracking.enabled true
spark.dynamicAllocation.initialExecutors    1
spark.dynamicAllocation.minExecutors    1
spark.dynamicAllocation.maxExecutors    4
spark.dynamicAllocation.executorIdleTimeout 60s
# spark.dynamicAllocation.schedulerBacklogTimeout 5s # 1s default

# Executor resources 
spark.executor.cores   2
spark.executor.memory  4G

# Delta Lake
# spark.sql.extensions    io.delta.sql.DeltaSparkSessionExtension
# spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
# spark.delta.logStore.class org.apache.spark.sql.delta.storage.S3SingleDriverLogStore
